logs:
    - name: system
      level: info
      formatter: "%d{%Y-%m-%d %H:%M:%S}%T%t%T%N%T%F%T[%p]%T[%c]%T%f:%l%T%m%n"
      appenders: 
          - type: FileAppender
            file: systemlog.txt
          - type: StdOutAppender
    - name: root
      level: info
      formatter: "%d{%Y-%m-%d %H:%M:%S}%T%t%T%N%T%F%T[%p]%T[%c]%T%f:%l%T%m%n"
      appenders: 
          - type: FileAppender
            file: rootlog.txt
