logs:
    - name: sys
      level: info
      formatter: "%d%T%m%n"
      appenders: 
          - type: FileAppender
            file: log.txt
          - type: StdOutAppender
    - name: test
      level: debug
      formatter: "%d%T"
      appenders: 
        - type: StdOutAppender
          file: log1.txt